### PR TITLE
doc: bump svgbobdoc to 0.3.0

### PR DESCRIPTION
**Pull request by ia0**
Hi,

Would it be possible release a version of `rlsf` (e.g. `0.2.1`) that uses `svgbobdoc` 0.3.0? Because the current one uses an old version of `svg` that triggers warnings with a recent nightly.

```
warning: the following packages contain code that will be rejected by a future version of Rust: svg v0.5.12
```

Thanks!

### CODE REVIEW

**Comment by ia0** [comment]
Hi @yvt

Could you take a look at this PR? It is needed to avoid compilation being broken once trailing semicolons are denied in expression macro body. See https://github.com/rust-lang/rust/issues/79813.

Thanks!

**Comment by yvt** [comment]
@ia0 Sorry for the delay! I redrew the figure because some graphical features were broken. Could you check the rendering just in case?

**Comment by ia0** [comment]
@yvt No worries, thanks for the redrew.

Here's the diff:

image
image

It looks good to me.

**Comment by yvt** [comment]
Thanks!

**Pull request merged**
